CREATE TABLE noteful_lists (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    listname TEXT NOT NULL
);

ALTER TABLE noteful_notes 
    ADD COLUMN
        list_id INTEGER REFERENCES noteful_lists(id)
        ON DELETE SET NULL;